
# html lang
language: en

# main menu navigation
menu:
  首页: /
  关于: /about
  归档: /archives
  标签: /tags

# Miscelaneous
favicon: /favicon.ico

# stylesheets loaded in the <head>
stylesheets:
- /css/style.css

# scripts loaded in the end of the body
scripts:
- /js/script.js
